//! x86_64 Linux ABI 系统调用表

use crate::syscall::{SyscallDef, abi::SyscallDomain};

macro_rules! sc {
    ($nr:expr, $name:expr) => {
        SyscallDef {
            nr: $nr,
            name: $name,
            domain: SyscallDomain::Unknown,
        }
    };
    ($nr:expr, $name:expr, $domain:expr) => {
        SyscallDef {
            nr: $nr,
            name: $name,
            domain: $domain,
        }
    };
}

pub const SYSCALL_TABLE: &[SyscallDef] = &[
    sc!(0, "read", SyscallDomain::Fs),
    sc!(1, "write", SyscallDomain::Fs),
    sc!(2, "open", SyscallDomain::Fs),
    sc!(3, "close", SyscallDomain::Fs),
    sc!(4, "stat", SyscallDomain::Fs),
    sc!(5, "fstat", SyscallDomain::Fs),
    sc!(6, "lstat", SyscallDomain::Fs),
    sc!(7, "poll", SyscallDomain::Fs),
    sc!(8, "lseek", SyscallDomain::Fs),
    sc!(9, "mmap", SyscallDomain::Mm),
    sc!(10, "mprotect", SyscallDomain::Mm),
    sc!(11, "munmap", SyscallDomain::Mm),
    sc!(12, "brk", SyscallDomain::Mm),
    sc!(13, "rt_sigaction", SyscallDomain::Task),
    sc!(14, "rt_sigprocmask", SyscallDomain::Task),
    sc!(15, "rt_sigreturn", SyscallDomain::Task),
    sc!(16, "ioctl", SyscallDomain::Fs),
    sc!(17, "pread64"),
    sc!(18, "pwrite64"),
    sc!(19, "readv"),
    sc!(20, "writev"),
    sc!(21, "access"),
    sc!(22, "pipe", SyscallDomain::Fs),
    sc!(23, "select", SyscallDomain::Fs),
    sc!(24, "sched_yield"),
    sc!(25, "mremap"),
    sc!(26, "msync"),
    sc!(27, "mincore"),
    sc!(28, "madvise"),
    sc!(29, "shmget"),
    sc!(30, "shmat"),
    sc!(31, "shmctl"),
    sc!(32, "dup", SyscallDomain::Fs),
    sc!(33, "dup2", SyscallDomain::Fs),
    sc!(34, "pause"),
    sc!(35, "nanosleep"),
    sc!(36, "getitimer"),
    sc!(37, "alarm"),
    sc!(38, "setitimer"),
    sc!(39, "getpid", SyscallDomain::Task),
    sc!(40, "sendfile"),
    sc!(41, "socket", SyscallDomain::Net),
    sc!(42, "connect", SyscallDomain::Net),
    sc!(43, "accept", SyscallDomain::Net),
    sc!(44, "sendto", SyscallDomain::Net),
    sc!(45, "recvfrom", SyscallDomain::Net),
    sc!(46, "sendmsg", SyscallDomain::Net),
    sc!(47, "recvmsg", SyscallDomain::Net),
    sc!(48, "shutdown", SyscallDomain::Net),
    sc!(49, "bind", SyscallDomain::Net),
    sc!(50, "listen", SyscallDomain::Net),
    sc!(51, "getsockname", SyscallDomain::Net),
    sc!(52, "getpeername", SyscallDomain::Net),
    sc!(53, "socketpair", SyscallDomain::Net),
    sc!(54, "setsockopt", SyscallDomain::Net),
    sc!(55, "getsockopt", SyscallDomain::Net),
    sc!(56, "clone", SyscallDomain::Task),
    sc!(57, "fork", SyscallDomain::Task),
    sc!(58, "vfork", SyscallDomain::Task),
    sc!(59, "execve", SyscallDomain::Task),
    sc!(60, "exit", SyscallDomain::Task),
    sc!(61, "wait4", SyscallDomain::Task),
    sc!(62, "kill", SyscallDomain::Task),
    sc!(63, "uname"),
    sc!(64, "semget"),
    sc!(65, "semop"),
    sc!(66, "semctl"),
    sc!(67, "shmdt"),
    sc!(68, "msgget"),
    sc!(69, "msgsnd"),
    sc!(70, "msgrcv"),
    sc!(71, "msgctl"),
    sc!(72, "fcntl", SyscallDomain::Fs),
    sc!(73, "flock"),
    sc!(74, "fsync"),
    sc!(75, "fdatasync"),
    sc!(76, "truncate"),
    sc!(77, "ftruncate"),
    sc!(78, "getdents"),
    sc!(79, "getcwd", SyscallDomain::Fs),
    sc!(80, "chdir", SyscallDomain::Fs),
    sc!(81, "fchdir"),
    sc!(82, "rename"),
    sc!(83, "mkdir"),
    sc!(84, "rmdir"),
    sc!(85, "creat"),
    sc!(86, "link"),
    sc!(87, "unlink"),
    sc!(88, "symlink"),
    sc!(89, "readlink"),
    sc!(90, "chmod"),
    sc!(91, "fchmod"),
    sc!(92, "chown"),
    sc!(93, "fchown"),
    sc!(94, "lchown"),
    sc!(95, "umask"),
    sc!(96, "gettimeofday"),
    sc!(97, "getrlimit"),
    sc!(98, "getrusage"),
    sc!(99, "sysinfo"),
    sc!(100, "times"),
    sc!(101, "ptrace"),
    sc!(102, "getuid"),
    sc!(103, "syslog"),
    sc!(104, "getgid"),
    sc!(105, "setuid"),
    sc!(106, "setgid"),
    sc!(107, "geteuid"),
    sc!(108, "getegid"),
    sc!(109, "setpgid", SyscallDomain::Task),
    sc!(110, "getppid", SyscallDomain::Task),
    sc!(111, "getpgrp", SyscallDomain::Task),
    sc!(112, "setsid", SyscallDomain::Task),
    sc!(113, "setreuid"),
    sc!(114, "setregid"),
    sc!(115, "getgroups"),
    sc!(116, "setgroups"),
    sc!(117, "setresuid"),
    sc!(118, "getresuid"),
    sc!(119, "setresgid"),
    sc!(120, "getresgid"),
    sc!(121, "getpgid", SyscallDomain::Task),
    sc!(122, "setfsuid"),
    sc!(123, "setfsgid"),
    sc!(124, "getsid"),
    sc!(125, "capget"),
    sc!(126, "capset"),
    sc!(127, "rt_sigpending"),
    sc!(128, "rt_sigtimedwait"),
    sc!(129, "rt_sigqueueinfo"),
    sc!(130, "rt_sigsuspend"),
    sc!(131, "sigaltstack"),
    sc!(132, "utime"),
    sc!(133, "mknod"),
    sc!(134, "uselib"),
    sc!(135, "personality"),
    sc!(136, "ustat"),
    sc!(137, "statfs"),
    sc!(138, "fstatfs"),
    sc!(139, "sysfs"),
    sc!(140, "getpriority"),
    sc!(141, "setpriority"),
    sc!(142, "sched_setparam"),
    sc!(143, "sched_getparam"),
    sc!(144, "sched_setscheduler"),
    sc!(145, "sched_getscheduler"),
    sc!(146, "sched_get_priority_max"),
    sc!(147, "sched_get_priority_min"),
    sc!(148, "sched_rr_get_interval"),
    sc!(149, "mlock"),
    sc!(150, "munlock"),
    sc!(151, "mlockall"),
    sc!(152, "munlockall"),
    sc!(153, "vhangup"),
    sc!(154, "modify_ldt"),
    sc!(155, "pivot_root"),
    sc!(156, "_sysctl"),
    sc!(157, "prctl"),
    sc!(158, "arch_prctl"),
    sc!(159, "adjtimex"),
    sc!(160, "setrlimit"),
    sc!(161, "chroot"),
    sc!(162, "sync"),
    sc!(163, "acct"),
    sc!(164, "settimeofday"),
    sc!(165, "mount"),
    sc!(166, "umount2"),
    sc!(167, "swapon"),
    sc!(168, "swapoff"),
    sc!(169, "reboot"),
    sc!(170, "sethostname"),
    sc!(171, "setdomainname"),
    sc!(172, "iopl"),
    sc!(173, "ioperm"),
    sc!(174, "create_module"),
    sc!(175, "init_module"),
    sc!(176, "delete_module"),
    sc!(177, "get_kernel_syms"),
    sc!(178, "query_module"),
    sc!(179, "quotactl"),
    sc!(180, "nfsservctl"),
    sc!(181, "getpmsg"),
    sc!(182, "putpmsg"),
    sc!(183, "afs_syscall"),
    sc!(184, "tuxcall"),
    sc!(185, "security"),
    sc!(186, "gettid", SyscallDomain::Task),
    sc!(187, "readahead"),
    sc!(188, "setxattr"),
    sc!(189, "lsetxattr"),
    sc!(190, "fsetxattr"),
    sc!(191, "getxattr"),
    sc!(192, "lgetxattr"),
    sc!(193, "fgetxattr"),
    sc!(194, "listxattr"),
    sc!(195, "llistxattr"),
    sc!(196, "flistxattr"),
    sc!(197, "removexattr"),
    sc!(198, "lremovexattr"),
    sc!(199, "fremovexattr"),
    sc!(200, "tkill", SyscallDomain::Task),
    sc!(201, "time"),
    sc!(202, "futex"),
    sc!(203, "sched_setaffinity"),
    sc!(204, "sched_getaffinity"),
    sc!(205, "set_thread_area"),
    sc!(206, "io_setup"),
    sc!(207, "io_destroy"),
    sc!(208, "io_getevents"),
    sc!(209, "io_submit"),
    sc!(210, "io_cancel"),
    sc!(211, "get_thread_area"),
    sc!(212, "lookup_dcookie"),
    sc!(213, "epoll_create"),
    sc!(214, "epoll_ctl_old"),
    sc!(215, "epoll_wait_old"),
    sc!(216, "remap_file_pages"),
    sc!(217, "getdents64", SyscallDomain::Fs),
    sc!(218, "set_tid_address"),
    sc!(219, "restart_syscall"),
    sc!(220, "semtimedop"),
    sc!(221, "fadvise64"),
    sc!(222, "timer_create"),
    sc!(223, "timer_settime"),
    sc!(224, "timer_gettime"),
    sc!(225, "timer_getoverrun"),
    sc!(226, "timer_delete"),
    sc!(227, "clock_settime"),
    sc!(228, "clock_gettime"),
    sc!(229, "clock_getres"),
    sc!(230, "clock_nanosleep"),
    sc!(231, "exit_group", SyscallDomain::Task),
    sc!(232, "epoll_wait"),
    sc!(233, "epoll_ctl"),
    sc!(234, "tgkill", SyscallDomain::Task),
    sc!(235, "utimes"),
    sc!(236, "vserver"),
    sc!(237, "mbind"),
    sc!(238, "set_mempolicy"),
    sc!(239, "get_mempolicy"),
    sc!(240, "mq_open"),
    sc!(241, "mq_unlink"),
    sc!(242, "mq_timedsend"),
    sc!(243, "mq_timedreceive"),
    sc!(244, "mq_notify"),
    sc!(245, "mq_getsetattr"),
    sc!(246, "kexec_load"),
    sc!(247, "waitid"),
    sc!(248, "add_key"),
    sc!(249, "request_key"),
    sc!(250, "keyctl"),
    sc!(251, "ioprio_set"),
    sc!(252, "ioprio_get"),
    sc!(253, "inotify_init"),
    sc!(254, "inotify_add_watch"),
    sc!(255, "inotify_rm_watch"),
    sc!(256, "migrate_pages"),
    sc!(257, "openat"),
    sc!(258, "mkdirat"),
    sc!(259, "mknodat"),
    sc!(260, "fchownat"),
    sc!(261, "futimesat"),
    sc!(262, "newfstatat"),
    sc!(263, "unlinkat"),
    sc!(264, "renameat"),
    sc!(265, "linkat"),
    sc!(266, "symlinkat"),
    sc!(267, "readlinkat"),
    sc!(268, "fchmodat"),
    sc!(269, "faccessat"),
    sc!(270, "pselect6"),
    sc!(271, "ppoll"),
    sc!(272, "unshare"),
    sc!(273, "set_robust_list"),
    sc!(274, "get_robust_list"),
    sc!(275, "splice"),
    sc!(276, "tee"),
    sc!(277, "sync_file_range"),
    sc!(278, "vmsplice"),
    sc!(279, "move_pages"),
    sc!(280, "utimensat"),
    sc!(281, "epoll_pwait"),
    sc!(282, "signalfd"),
    sc!(283, "timerfd_create"),
    sc!(284, "eventfd"),
    sc!(285, "fallocate"),
    sc!(286, "timerfd_settime"),
    sc!(287, "timerfd_gettime"),
    sc!(288, "accept4"),
    sc!(289, "signalfd4"),
    sc!(290, "eventfd2"),
    sc!(291, "epoll_create1"),
    sc!(292, "dup3"),
    sc!(293, "pipe2", SyscallDomain::Fs),
    sc!(294, "inotify_init1"),
    sc!(295, "preadv"),
    sc!(296, "pwritev"),
    sc!(297, "rt_tgsigqueueinfo"),
    sc!(298, "perf_event_open"),
    sc!(299, "recvmmsg"),
    sc!(300, "fanotify_init"),
    sc!(301, "fanotify_mark"),
    sc!(302, "prlimit64"),
    sc!(303, "name_to_handle_at"),
    sc!(304, "open_by_handle_at"),
    sc!(305, "clock_adjtime"),
    sc!(306, "syncfs"),
    sc!(307, "sendmmsg"),
    sc!(308, "setns"),
    sc!(309, "getcpu"),
    sc!(310, "process_vm_readv"),
    sc!(311, "process_vm_writev"),
    sc!(312, "kcmp"),
    sc!(313, "finit_module"),
    sc!(314, "sched_setattr"),
    sc!(315, "sched_getattr"),
    sc!(316, "renameat2"),
    sc!(317, "seccomp"),
    sc!(318, "getrandom"),
    sc!(319, "memfd_create"),
    sc!(320, "kexec_file_load"),
    sc!(321, "bpf"),
    sc!(322, "execveat"),
    sc!(323, "userfaultfd"),
    sc!(324, "membarrier"),
    sc!(325, "mlock2"),
    sc!(326, "copy_file_range"),
    sc!(327, "preadv2"),
    sc!(328, "pwritev2"),
    sc!(329, "pkey_mprotect"),
    sc!(330, "pkey_alloc"),
    sc!(331, "pkey_free"),
    sc!(332, "statx"),
    sc!(333, "io_pgetevents"),
    sc!(334, "rseq"),
    // x86_64 Linux ABI reserves 335..423; keep explicit placeholders so the
    // exported table stays dense across the full ABI number range.
    sc!(335, "reserved"),
    sc!(336, "reserved"),
    sc!(337, "reserved"),
    sc!(338, "reserved"),
    sc!(339, "reserved"),
    sc!(340, "reserved"),
    sc!(341, "reserved"),
    sc!(342, "reserved"),
    sc!(343, "reserved"),
    sc!(344, "reserved"),
    sc!(345, "reserved"),
    sc!(346, "reserved"),
    sc!(347, "reserved"),
    sc!(348, "reserved"),
    sc!(349, "reserved"),
    sc!(350, "reserved"),
    sc!(351, "reserved"),
    sc!(352, "reserved"),
    sc!(353, "reserved"),
    sc!(354, "reserved"),
    sc!(355, "reserved"),
    sc!(356, "reserved"),
    sc!(357, "reserved"),
    sc!(358, "reserved"),
    sc!(359, "reserved"),
    sc!(360, "reserved"),
    sc!(361, "reserved"),
    sc!(362, "reserved"),
    sc!(363, "reserved"),
    sc!(364, "reserved"),
    sc!(365, "reserved"),
    sc!(366, "reserved"),
    sc!(367, "reserved"),
    sc!(368, "reserved"),
    sc!(369, "reserved"),
    sc!(370, "reserved"),
    sc!(371, "reserved"),
    sc!(372, "reserved"),
    sc!(373, "reserved"),
    sc!(374, "reserved"),
    sc!(375, "reserved"),
    sc!(376, "reserved"),
    sc!(377, "reserved"),
    sc!(378, "reserved"),
    sc!(379, "reserved"),
    sc!(380, "reserved"),
    sc!(381, "reserved"),
    sc!(382, "reserved"),
    sc!(383, "reserved"),
    sc!(384, "reserved"),
    sc!(385, "reserved"),
    sc!(386, "reserved"),
    sc!(387, "reserved"),
    sc!(388, "reserved"),
    sc!(389, "reserved"),
    sc!(390, "reserved"),
    sc!(391, "reserved"),
    sc!(392, "reserved"),
    sc!(393, "reserved"),
    sc!(394, "reserved"),
    sc!(395, "reserved"),
    sc!(396, "reserved"),
    sc!(397, "reserved"),
    sc!(398, "reserved"),
    sc!(399, "reserved"),
    sc!(400, "reserved"),
    sc!(401, "reserved"),
    sc!(402, "reserved"),
    sc!(403, "reserved"),
    sc!(404, "reserved"),
    sc!(405, "reserved"),
    sc!(406, "reserved"),
    sc!(407, "reserved"),
    sc!(408, "reserved"),
    sc!(409, "reserved"),
    sc!(410, "reserved"),
    sc!(411, "reserved"),
    sc!(412, "reserved"),
    sc!(413, "reserved"),
    sc!(414, "reserved"),
    sc!(415, "reserved"),
    sc!(416, "reserved"),
    sc!(417, "reserved"),
    sc!(418, "reserved"),
    sc!(419, "reserved"),
    sc!(420, "reserved"),
    sc!(421, "reserved"),
    sc!(422, "reserved"),
    sc!(423, "reserved"),
    sc!(424, "pidfd_send_signal"),
    sc!(425, "io_uring_setup"),
    sc!(426, "io_uring_enter"),
    sc!(427, "io_uring_register"),
    sc!(428, "open_tree"),
    sc!(429, "move_mount"),
    sc!(430, "fsopen"),
    sc!(431, "fsconfig"),
    sc!(432, "fsmount"),
    sc!(433, "fspick"),
    sc!(434, "pidfd_open"),
    sc!(435, "clone3"),
    sc!(436, "close_range"),
    sc!(437, "openat2"),
    sc!(438, "pidfd_getfd"),
    sc!(439, "faccessat2"),
    sc!(440, "process_madvise"),
    sc!(441, "epoll_pwait2"),
    sc!(442, "mount_setattr"),
    sc!(443, "quotactl_fd"),
    sc!(444, "landlock_create_ruleset"),
    sc!(445, "landlock_add_rule"),
    sc!(446, "landlock_restrict_self"),
    sc!(447, "memfd_secret"),
    sc!(448, "process_mrelease"),
    sc!(449, "futex_waitv"),
    sc!(450, "set_mempolicy_home_node"),
    sc!(451, "cachestat"),
    sc!(452, "fchmodat2"),
    sc!(453, "map_shadow_stack"),
    sc!(454, "futex_wake"),
    sc!(455, "futex_wait"),
    sc!(456, "futex_requeue"),
    sc!(457, "statmount"),
    sc!(458, "listmount"),
    sc!(459, "lsm_get_self_attr"),
    sc!(460, "lsm_set_self_attr"),
    sc!(461, "lsm_list_modules"),
];
